import re
import json


def deep_set(dic, keys, value):
    for i, key in enumerate(keys[:-1]):
        if isinstance(key, int):
            # Ensure dic is a list for integer indexing
            while isinstance(dic, dict) and key not in dic:
                dic[key] = []
            if isinstance(dic, list):
                while len(dic) <= key:
                    dic.append({})
            dic = dic[key]
        else:
            if key not in dic:
                # Next key determines the type of value to initialize: list for int, dict for str
                next_key = keys[i + 1]
                dic[key] = [] if isinstance(next_key, int) else {}
            dic = dic[key]

    # Handle the last key
    if isinstance(keys[-1], int):
        if not isinstance(dic, list):
            dic[keys[-1]] = []  # Initialize a list if the last key is an integer
        while len(dic) <= keys[-1]:
            dic.append(None)
        dic[keys[-1]] = value
    else:
        dic[keys[-1]] = value


def parse_key(key):
    """Parse a key into a list of keys, converting '[index]' into integer keys."""
    parts = re.split(r"\.|\[|\]", key)
    keys = [
        int(part) if part.isdigit() else part for part in parts if part
    ]  # Remove empty strings
    return keys


def decode_to_json(decode_content: list):
    result = {}
    for content in decode_content:
        key, value = content.split("=")
        keys = parse_key(key)
        deep_set(result, keys, value)
    result = result.get("Events", [{}])[0]
    return result


# Example usage

if __name__ == "__main__":
    decode_content = [
        "Events[0].Action=Pulse",
        "Events[0].Class=Traffic",
        "Events[0].Code=TrafficJunction",
        "Events[0].CommInfo.Country=DNK",
        "Events[0].CommInfo.GPSInfo.Latitude=0.000000",
        "Events[0].CommInfo.GPSInfo.Longitude=0.000000",
        "Events[0].CommInfo.RadarInfo.CoordinateX=0.000000",
        "Events[0].CommInfo.RadarInfo.CoordinateY=0.000000",
        "Events[0].CommInfo.Seat[0].SafeBelt=unknow",
        "Events[0].CommInfo.Seat[0].Status[0]=CallingUnknown",
        "Events[0].CommInfo.Seat[0].Status[1]=SmokingUnknown",
        "Events[0].CommInfo.Seat[0].SunShade=unknow",
        "Events[0].CommInfo.Seat[0].Type=Main",
        "Events[0].CommInfo.Seat[1].SafeBelt=unknow",
        "Events[0].CommInfo.Seat[1].Status[0]=CallingUnknown",
        "Events[0].CommInfo.Seat[1].Status[1]=SmokingUnknown",
        "Events[0].CommInfo.Seat[1].SunShade=unknow",
        "Events[0].CommInfo.Seat[1].Type=Slave",
        "Events[0].CommInfo.SnapCategory=Motor",
        "Events[0].CommInfo.StandardVehicleType=Pickup",
        "Events[0].CommInfo.VehicleTypeByFunc=Unknown",
        "Events[0].CountInGroup=1",
        "Events[0].CustomSeq=0",
        "Events[0].DSTTune=0",
        "Events[0].EventBaseInfo.Action=Pulse",
        "Events[0].EventBaseInfo.Code=TrafficJunction",
        "Events[0].EventBaseInfo.Index=0",
        "Events[0].EventID=2739",
        "Events[0].EventSeq=2739",
        "Events[0].FrameSequence=866974",
        "Events[0].GroupID=413447617",
        "Events[0].IndexInGroup=1",
        "Events[0].JunctionDirection=Obverse",
        "Events[0].Lane=2",
        "Events[0].MainSeat=unknow",
        "Events[0].Mark=215",
        "Events[0].Name=TrafficTollGate0",
        "Events[0].Object.Action=Appear",
        "Events[0].Object.AxleCount=0",
        "Events[0].Object.BelongID=19972",
        "Events[0].Object.BoundingBox[0]=4568",
        "Events[0].Object.BoundingBox[1]=4080",
        "Events[0].Object.BoundingBox[2]=4856",
        "Events[0].Object.BoundingBox[3]=4288",
        "Events[0].Object.Category=Unknown",
        "Events[0].Object.Center[0]=4712",
        "Events[0].Object.Center[1]=4184",
        "Events[0].Object.Confidence=222",
        "Events[0].Object.Country=DNK",
        "Events[0].Object.FrameSequence=866947",
        "Events[0].Object.Image.Height=64",
        "Events[0].Object.Image.Length=2745",
        "Events[0].Object.Image.Offset=988176",
        "Events[0].Object.Image.Width=96",
        "Events[0].Object.MainColor[0]=255",
        "Events[0].Object.MainColor[1]=255",
        "Events[0].Object.MainColor[2]=255",
        "Events[0].Object.MainColor[3]=0",
        "Events[0].Object.MainSeat.DriverCalling=CallingUnknown",
        "Events[0].Object.MainSeat.DriverSmoking=SmokingUnknown",
        "Events[0].Object.MainSeat.SafeBelt=unknow",
        "Events[0].Object.ObjectID=19972",
        "Events[0].Object.ObjectType=Plate",
        "Events[0].Object.OriginalBoundingBox[0]=1142",
        "Events[0].Object.OriginalBoundingBox[1]=829",
        "Events[0].Object.OriginalBoundingBox[2]=1214",
        "Events[0].Object.OriginalBoundingBox[3]=868",
        "Events[0].Object.RelativeID=19972",
        "Events[0].Object.SerialUUID=",
        "Events[0].Object.ShotFrame=true",
        "Events[0].Object.Source=544932192256.000000",
        "Events[0].Object.Speed=0",
        "Events[0].Object.SpeedTypeInternal=0",
        "Events[0].Object.SubSeat.DriverCalling=CallingUnknown",
        "Events[0].Object.SubSeat.DriverSmoking=SmokingUnknown",
        "Events[0].Object.SubSeat.SafeBelt=unknow",
        "Events[0].Object.Text=22C08088",
        "Events[0].Object.TrackType=0",
        "Events[0].PTS=47267399980.000000",
        "Events[0].RadarSpeedSetTime=0.000000",
        "Events[0].RadarSpeedSourceTime=0.000000",
        "Events[0].RoadwayNumber=2",
        "Events[0].RuleID=31",
        "Events[0].SceneImage.Length=988176",
        "Events[0].SceneImage.Offset=0",
        "Events[0].Sequence=1",
        "Events[0].Source=544932192256.000000",
        "Events[0].Speed=0",
        "Events[0].SubSeat=unknow",
        "Events[0].TextSource=0",
        "Events[0].TimeZone=12",
        "Events[0].TrafficCar.BoundingBox[0]=4568",
        "Events[0].TrafficCar.BoundingBox[1]=4080",
        "Events[0].TrafficCar.BoundingBox[2]=4856",
        "Events[0].TrafficCar.BoundingBox[3]=4288",
        "Events[0].TrafficCar.CountInGroup=1",
        "Events[0].TrafficCar.Country=DNK",
        "Events[0].TrafficCar.CustomFlowDirection=Car go out",
        "Events[0].TrafficCar.CustomRoadwayDirection=",
        "Events[0].TrafficCar.Direction=0",
        "Events[0].TrafficCar.DrivingDirection[0]=Approach",
        "Events[0].TrafficCar.DrivingDirection[1]=Car go out",
        "Events[0].TrafficCar.DrivingDirection[2]=Car come in",
        "Events[0].TrafficCar.Event=TrafficJunction",
        "Events[0].TrafficCar.FlowDirection=2",
        "Events[0].TrafficCar.GroupID=413447617",
        "Events[0].TrafficCar.IndexInGroup=1",
        "Events[0].TrafficCar.Lane=2",
        "Events[0].TrafficCar.LowerSpeedLimit=60",
        "Events[0].TrafficCar.MachineName=9K0D4D5PAJCA9FE",
        "Events[0].TrafficCar.OverSpeedMargin=0",
        "Events[0].TrafficCar.PhysicalLane=1",
        "Events[0].TrafficCar.PlateColor=White",
        "Events[0].TrafficCar.PlateNumber=22C08088",
        "Events[0].TrafficCar.PlateType=Unknown",
        "Events[0].TrafficCar.RoadwayNo=",
        "Events[0].TrafficCar.RouteNo=",
        "Events[0].TrafficCar.Speed=0",
        "Events[0].TrafficCar.UTC=1720113889",
        "Events[0].TrafficCar.UnderSpeedMargin=10",
        "Events[0].TrafficCar.UpperSpeedLimit=70",
        "Events[0].TrafficCar.VehicleBoundingBox[0]=3384",
        "Events[0].TrafficCar.VehicleBoundingBox[1]=2272",
        "Events[0].TrafficCar.VehicleBoundingBox[2]=5480",
        "Events[0].TrafficCar.VehicleBoundingBox[3]=4544",
        "Events[0].TrafficCar.VehicleColor=Silver",
        "Events[0].TrafficCar.VehicleColorRGB[0]=192",
        "Events[0].TrafficCar.VehicleColorRGB[1]=192",
        "Events[0].TrafficCar.VehicleColorRGB[2]=192",
        "Events[0].TrafficCar.VehicleColorRGB[3]=0",
        "Events[0].TrafficCar.VehicleSign=Mitsubishi",
        "Events[0].TrafficCar.VehicleSize=Light-duty",
        "Events[0].TrafficCar.ViolationCode=",
        "Events[0].TrafficCar.ViolationDesc=ANPR",
        "Events[0].TrafficCar.ViolationName=ANPR",
        "Events[0].UTC=1720113889",
        "Events[0].UTCMS=606",
        "Events[0].Vehicle.Action=Appear",
        "Events[0].Vehicle.BelongID=19972",
        "Events[0].Vehicle.BoundingBox[0]=3384",
        "Events[0].Vehicle.BoundingBox[1]=2272",
        "Events[0].Vehicle.BoundingBox[2]=5480",
        "Events[0].Vehicle.BoundingBox[3]=4544",
        "Events[0].Vehicle.BrandYear=0",
        "Events[0].Vehicle.BrandYearText=",
        "Events[0].Vehicle.CarLogoIndex=36",
        "Events[0].Vehicle.CarSeriesIndex=0",
        "Events[0].Vehicle.CarWindow.BoundingBox[0]=0",
        "Events[0].Vehicle.CarWindow.BoundingBox[1]=0",
        "Events[0].Vehicle.CarWindow.BoundingBox[2]=0",
        "Events[0].Vehicle.CarWindow.BoundingBox[3]=0",
        "Events[0].Vehicle.Category=Pickup",
        "Events[0].Vehicle.CategoryConfidence=0",
        "Events[0].Vehicle.Center[0]=4432",
        "Events[0].Vehicle.Center[1]=3408",
        "Events[0].Vehicle.Confidence=254",
        "Events[0].Vehicle.DriverFace[0][0]=0",
        "Events[0].Vehicle.DriverFace[0][1]=0",
        "Events[0].Vehicle.DriverFace[0][2]=0",
        "Events[0].Vehicle.DriverFace[0][3]=0",
        "Events[0].Vehicle.DriverFace[1][0]=0",
        "Events[0].Vehicle.DriverFace[1][1]=0",
        "Events[0].Vehicle.DriverFace[1][2]=0",
        "Events[0].Vehicle.DriverFace[1][3]=0",
        "Events[0].Vehicle.Extra.directionRun=1",
        "Events[0].Vehicle.FrameSequence=866947",
        "Events[0].Vehicle.FusionInfo.BelongID=19972",
        "Events[0].Vehicle.FusionInfo.CartPosX=0.000000",
        "Events[0].Vehicle.FusionInfo.CartPosY=0.000000",
        "Events[0].Vehicle.FusionInfo.GpsPosValid=0",
        "Events[0].Vehicle.FusionInfo.GpsPostion.Latitude=0.000000",
        "Events[0].Vehicle.FusionInfo.GpsPostion.Longitude=0.000000",
        "Events[0].Vehicle.FusionInfo.ObjectSource=0",
        "Events[0].Vehicle.FusionInfo.RadarCoorXyValid=0",
        "Events[0].Vehicle.FusionInfo.Speed=0.000000",
        "Events[0].Vehicle.FusionInfo.SpeedValid=0",
        "Events[0].Vehicle.FusionInfo.SpeedX=0.000000",
        "Events[0].Vehicle.FusionInfo.SpeedY=0.000000",
        "Events[0].Vehicle.Image.Length=0",
        "Events[0].Vehicle.Image.Offset=0",
        "Events[0].Vehicle.MainColor[0]=192",
        "Events[0].Vehicle.MainColor[1]=192",
        "Events[0].Vehicle.MainColor[2]=192",
        "Events[0].Vehicle.MainColor[3]=0",
        "Events[0].Vehicle.MainSeat.DriverCalling=CallingUnknown",
        "Events[0].Vehicle.MainSeat.DriverSmoking=SmokingUnknown",
        "Events[0].Vehicle.MainSeat.SafeBelt=unknow",
        "Events[0].Vehicle.MainSeat.SunShade=unknow",
        "Events[0].Vehicle.ObjectID=19972",
        "Events[0].Vehicle.ObjectType=Vehicle",
        "Events[0].Vehicle.OriginalBoundingBox[0]=846",
        "Events[0].Vehicle.OriginalBoundingBox[1]=490",
        "Events[0].Vehicle.OriginalBoundingBox[2]=1370",
        "Events[0].Vehicle.OriginalBoundingBox[3]=916",
        "Events[0].Vehicle.PTZ[0]=0",
        "Events[0].Vehicle.PTZ[1]=0",
        "Events[0].Vehicle.PTZ[2]=0",
        "Events[0].Vehicle.Plate.BoundingBox[0]=4568",
        "Events[0].Vehicle.Plate.BoundingBox[1]=4080",
        "Events[0].Vehicle.Plate.BoundingBox[2]=4864",
        "Events[0].Vehicle.Plate.BoundingBox[3]=4280",
        "Events[0].Vehicle.Plate.Category=Unknown",
        "Events[0].Vehicle.Plate.FrameSequence=866947",
        "Events[0].Vehicle.Plate.MainColor[0]=0",
        "Events[0].Vehicle.Plate.MainColor[1]=0",
        "Events[0].Vehicle.Plate.MainColor[2]=0",
        "Events[0].Vehicle.Plate.MainColor[3]=0",
        "Events[0].Vehicle.Plate.ObjectID=19972",
        "Events[0].Vehicle.Plate.ObjectType=Plate",
        "Events[0].Vehicle.Plate.PlateCentroid[0]=0",
        "Events[0].Vehicle.Plate.PlateCentroid[1]=0",
        "Events[0].Vehicle.Plate.Text=Unknown",
        "Events[0].Vehicle.RelativeID=19972",
        "Events[0].Vehicle.SerialUUID=",
        "Events[0].Vehicle.ShotFrame=true",
        "Events[0].Vehicle.Source=544932192256.000000",
        "Events[0].Vehicle.Speed=0",
        "Events[0].Vehicle.SpeedTypeInternal=0",
        "Events[0].Vehicle.SubBrand=0",
        "Events[0].Vehicle.SubSeat.DriverCalling=CallingUnknown",
        "Events[0].Vehicle.SubSeat.DriverSmoking=SmokingUnknown",
        "Events[0].Vehicle.SubSeat.SafeBelt=unknow",
        "Events[0].Vehicle.SubSeat.SunShade=unknow",
        "Events[0].Vehicle.Text=Mitsubishi",
        "Events[0].Vehicle.VehiclePosture=1",
        "Events[0].Vehicle.VehicleSignConfidence=0",
        "Events[0].Vehicle.carLenMode=0",
        "Events[0].Vehicle.carLength=0",
        "Events[0].Vehicle.carTripLineDirection=0",
        "Events[0].ViolationSnapSource=0",
        "Events[0].VsfGrpIdx=0",
        "Events[0].firstSnapUTC=1720113889",
    ]
    # decode_content = [
    #     "Events[0].Candidates[0].Person.Name=Thanh",
    #     "Events[0].Candidates[0].Person.UID=1346",
    #     "Events[0].Candidates[0].Similarity=99",
    #     "Events[0].Faces[0].BoundingBox[0]=2312",
    #     "Events[0].Faces[0].BoundingBox[1]=4720",
    #     "Events[0].Faces[0].BoundingBox[2]=2824",
    #     "Events[0].Faces[0].BoundingBox[3]=5680",
    #     "Events[0].Name=FaceRecognition",
    #     "Events[0].Object.Action=Appear",
    #     "Events[0].Object.Age=29",
    #     "Events[0].Object.Angle[0]=0",
    #     "Events[0].Object.Angle[1]=0",
    #     "Events[0].Object.Angle[2]=0",
    #     "Events[0].Object.Attractive=17",
    #     "Events[0].Object.Beard=1",
    #     "Events[0].Object.BoundingBox[0]=2312",
    #     "Events[0].Object.BoundingBox[1]=4720",
    #     "Events[0].Object.BoundingBox[2]=2824",
    #     "Events[0].Object.BoundingBox[3]=5680",
    #     "Events[0].Object.Category=Normal",
    #     "Events[0].Object.Center[0]=2568",
    #     "Events[0].Object.Center[1]=5200",
    #     "Events[0].Object.Complexion=1",
    #     "Events[0].Object.Confidence=200",
    #     "Events[0].Object.Emotion=Neutral",
    #     "Events[0].Object.Eye=1",
    #     "Events[0].Object.FaceAlignScore=0",
    #     "Events[0].Object.FaceQuality=0",
    #     "Events[0].Object.Feature[0]=Neutral",
    #     "Events[0].Object.Feature[1]=NoGlasses",
    #     "Events[0].Object.FrameSequence=12366328",
    #     "Events[0].Object.Glass=1",
    #     "Events[0].Object.Image.Height=960",
    #     "Events[0].Object.Image.Length=55643",
    #     "Events[0].Object.Image.Offset=154296",
    #     "Events[0].Object.Image.Width=512",
    #     "Events[0].Object.Mask=1",
    #     "Events[0].Object.Mouth=1",
    #     "Events[0].Object.Nation=2",
    #     "Events[0].Object.ObjectID=1",
    #     "Events[0].Object.ObjectType=HumanFace",
    #     "Events[0].Object.Race=1",
    #     "Events[0].Object.Recnum=1",
    #     "Events[0].Object.Recresult[0].DbId=53",
    #     "Events[0].Object.Recresult[0].FeatureId=1346",
    #     "Events[0].Object.Recresult[0].Similarity=99",
    #     "Events[0].Object.RelativeID=12366328",
    #     "Events[0].Objects[0].BoundingBox[0]=2312",
    #     "Events[0].Objects[0].BoundingBox[1]=4720",
    #     "Events[0].Objects[0].BoundingBox[2]=2824",
    #     "Events[0].Objects[0].BoundingBox[3]=5680",
    #     "Events[0].UTC=1719922486",
    # ]
    json_data = decode_to_json(decode_content)
    print(json.dumps(json_data, indent=4))
