from app.services.camera_settings.setting_camera_traffic_detection_services import setting_camera_traffic_services as st_camera_traffic_sv  # noqa
from app.services.camera_settings.setting_crowd_detection_services import setting_crowd_detection_services as st_crowd_sv  # noqa
from app.services.camera_settings.setting_detect_items_forgotten_services import setting_detect_items_forgotten_services as st_item_forgotten_sv  # noqa
from app.services.camera_settings.setting_tampering_services import setting_tampering_services as st_tampering_sv  # noqa
from app.services.camera_settings.setting_uniform_detection_services import setting_uniform_services as st_uniform_sv  # noqa
from app.services.camera_settings.setting_lane_services import setting_lane_services as st_lane_sv  # noqa