from enum import Enum

FACE_RECOGNITION_EXCHANGES = "FACE_RECOGNITION_EXCHANGES"
IDENTIFY_UNIFORMS_EXCHANGES = "IDENTIFY_UNIFORMS_EXCHANGES"
crowd = "CROWD_DETECTION_EXCHANGES"
plate_number = "PLATE_NUMBER_EXCHANGES"
WEAPON_IDENTIFICATION_EXCHANGES = "WEAPON_IDENTIFICATION_EXCHANGES"
DETECT_ITEMS_FORGOTTEN_EXCHANGES = "DETECT_ITEMS_FORGOTTEN_EXCHANGES"
CHECK_STATUS_SERVER_EXCHANGES = "CHECK_STATUS_SERVER_EXCHANGES"
CHECK_INFO_SERVER_EXCHANGES = "CHECK_INFO_SERVER_EXCHANGES"
loitering = "LOITERING_DETECTION_EXCHANGES"
CAMERA_TAMPERING_EXCHANGES = "CAMERA_TAMPERING_EXCHANGES"
CAMERA_TRAFFIC_SIGNAL_EXCHANGES = "CAMERA_TRAFFIC_SIGNAL_EXCHANGES"
illegal_parking = "ILLEGAL_PARKING_EXCHANGES"
tripwire = "TRIPWIRE_EXCHANGES"
LINE_VIOLATION_EXCHANGES = "LINE_VIOLATION_EXCHANGES"  # Lấn vạch kẻ đường
LANE_VIOLATION_EXCHANGES = "LANE_VIOLATION_EXCHANGES"  # Lấn làn đường
WRONG_WAY_EXCHANGES = "WRONG_WAY_EXCHANGES"  # Đi ngược chiều
LEAVING_EXCHANGES = "LEAVING_EXCHANGES"  # Rời khỏi khu vực
intrusion = "INTRUSION_EXCHANGES"  # Xâm nhập khu vực
obj_attr = "OBJ_ATTR_EXCHANGE"

queue_data = {
    FACE_RECOGNITION_EXCHANGES: "FACE_RECOGNITION_QUEUE",
    IDENTIFY_UNIFORMS_EXCHANGES: "IDENTIFY_UNIFORMS_QUEUE",
    crowd: "CROWD_DETECTION_QUEUE",
    plate_number: "PLATE_NUMBER_QUEUE",
    WEAPON_IDENTIFICATION_EXCHANGES: "WEAPON_IDENTIFICATION_QUEUE",
    DETECT_ITEMS_FORGOTTEN_EXCHANGES: "DETECT_ITEMS_FORGOTTEN_QUEUE",
    loitering: "LOITERING_DETECTION_QUEUE",
    CAMERA_TAMPERING_EXCHANGES: "CAMERA_TAMPERING_QUEUE",
    CAMERA_TRAFFIC_SIGNAL_EXCHANGES: "CAMERA_TRAFFIC_SIGNAL_QUEUE",
    illegal_parking: "ILLEGAL_PARKING_QUEUE",
    tripwire: "TRIPWIRE_QUEUE",
    LINE_VIOLATION_EXCHANGES: "LINE_VIOLATION_QUEUE",
    LANE_VIOLATION_EXCHANGES: "LANE_VIOLATION_QUEUE",
    WRONG_WAY_EXCHANGES: "WRONG_WAY_QUEUE",
    LEAVING_EXCHANGES: "LEAVING_QUEUE",
    intrusion: "INTRUSION_QUEUE",
    obj_attr: "OBJ_ATTR_QUEUE",
}

type_service_name = {
    FACE_RECOGNITION_EXCHANGES: "Khuôn mặt",
    IDENTIFY_UNIFORMS_EXCHANGES: "Đồng phục",
    "crowd": "Đám đông",
    "plate_number": "Biển số",
    DETECT_ITEMS_FORGOTTEN_EXCHANGES: "Bỏ rơi",
    "loitering": "Lảng vảng",
    CAMERA_TAMPERING_EXCHANGES: "Phá hoại",
    CAMERA_TRAFFIC_SIGNAL_EXCHANGES: "Tín hiệu giao thông",
    "illegal_parking": "Đậu đỗ trái phép",
    "tripwire": "Hàng rào ảo",
    LINE_VIOLATION_EXCHANGES: "Lấn vạch",
    LANE_VIOLATION_EXCHANGES: "Lấn làn",
    WRONG_WAY_EXCHANGES: "Đi ngược chiều",
    "leaving": "Rời vị trí",
    "intrusion": "Xâm nhập",
    "obj_attr": "Thuộc tính đối tượng",
}


class TypeServiceKey(str, Enum):
    FACE_RECOGNITION_EXCHANGES = "FACE_RECOGNITION_EXCHANGES"
    IDENTIFY_UNIFORMS_EXCHANGES = "IDENTIFY_UNIFORMS_EXCHANGES"
    crowd = "CROWD_DETECTION_EXCHANGES"
    plate_number = "PLATE_NUMBER_EXCHANGES"
    WEAPON_IDENTIFICATION_EXCHANGES = "WEAPON_IDENTIFICATION_EXCHANGES"
    DETECT_ITEMS_FORGOTTEN_EXCHANGES = "DETECT_ITEMS_FORGOTTEN_EXCHANGES"
    CHECK_STATUS_SERVER_EXCHANGES = "CHECK_STATUS_SERVER_EXCHANGES"
    CHECK_INFO_SERVER_EXCHANGES = "CHECK_INFO_SERVER_EXCHANGES"
    loitering = "LOITERING_DETECTION_EXCHANGES"
    CAMERA_TAMPERING_EXCHANGES = "CAMERA_TAMPERING_EXCHANGES"
    CAMERA_TRAFFIC_SIGNAL_EXCHANGES = "CAMERA_TRAFFIC_SIGNAL_EXCHANGES"
    illegal_parking = "ILLEGAL_PARKING_EXCHANGES"
    tripwire = "TRIPWIRE_EXCHANGES"
    LINE_VIOLATION_EXCHANGES = "LINE_VIOLATION_EXCHANGES"  # Lấn vạch kẻ đường
    LANE_VIOLATION_EXCHANGES = "LANE_VIOLATION_EXCHANGES"  # Lấn làn đường
    WRONG_WAY_EXCHANGES = "WRONG_WAY_EXCHANGES"  # Đi ngược chiều
    leaving = "LEAVING_EXCHANGES"  # Rời khỏi khu vực
    intrusion = "INTRUSION_EXCHANGES"  # Xâm nhập khu vực
    obj_attr = "OBJ_ATTR_EXCHANGE"
