apiVersion: v1
kind: Service
metadata:
  name: clusterip-svc
spec:
#  type: ClusterIP # default
  selector:
    app: app1 # service này sẽ chọn tất cả các container có label là app1
  ports:
    - protocol: TCP
      port: 8081 # service port , port của service này
      targetPort: 8080 # container port