# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tapi.proto\x12\x03\x61pi\"\x1a\n\x03\x42ox\x12\x13\n\x0b\x63oordinates\x18\x01 \x03(\x02\"\x1c\n\x07Request\x12\x11\n\tshare_key\x18\x01 \x01(\t\"f\n\x08Response\x12\x17\n\x05\x62oxes\x18\x01 \x03(\x0b\x32\x08.api.Box\x12\x0e\n\x06labels\x18\x02 \x03(\t\x12\x0e\n\x06scores\x18\x03 \x03(\x02\x12!\n\x0f\x64\x65tections_sort\x18\x04 \x03(\x0b\x32\x08.api.Box20\n\x06YOLOv5\x12&\n\x07Predict\x12\x0c.api.Request\x1a\r.api.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_BOX']._serialized_start=18
  _globals['_BOX']._serialized_end=44
  _globals['_REQUEST']._serialized_start=46
  _globals['_REQUEST']._serialized_end=74
  _globals['_RESPONSE']._serialized_start=76
  _globals['_RESPONSE']._serialized_end=178
  _globals['_YOLOV5']._serialized_start=180
  _globals['_YOLOV5']._serialized_end=228
# @@protoc_insertion_point(module_scope)
